/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author Nihal
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
//import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import java.awt.event.ActionListener;

/**
 *
 * @author yum
 */
public  class interface1 extends JFrame  {
         adminpanel admpl;
    /**
     * Creates new form interface1
     */
    public interface1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Connectez-vous! ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(880, 240, 480, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGIN.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(820, 340, 50, 50);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(880, 350, 340, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-password-48.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(820, 430, 50, 48);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(880, 440, 340, 40);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
                   public void actionPerformed(ActionEvent e) {
                   // admpl.setVisible(true);
                   jButton1ActionPerformed();
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(880, 520, 340, 60);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Chers utilisateurs !");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 290, 410, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cette application est faite pour les medecins , les patients denotre clinique \"Nour\" ; Si vous êtes un ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 410, 570, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("medecin , veuillez contacter l'administration pour vous donner votre nom utilisateur et mot de passe ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 430, 560, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Si vous êtes un patient , veuillez contacter votre medecin soignat pour vous donner votre identifiant");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 450, 560, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("et le mot de passe . Merci pour votre attention !");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 470, 540, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ADMINLOGIN (1).png"))); // NOI18N
        jLabel1.setLabelFor(jPanel1);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1ActionPerformed() {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String log=jTextField1.getText();
        String pass=new String(jPasswordField1.getPassword());
        Frame frame=new Frame();
            Map<String,String>users=new HashMap<String, String>();
            users.put("admin", "admin");
            //users.put("Medecin", "goshifts");
            //users.put("patient", "istockshelves");
                    for (Map.Entry<String, String> entry : users.entrySet()) {
                        String key = entry.getKey();
                        String value = entry.getValue();
                        if(key.compareTo(log) == 0 ){
                            if (value.compareTo(pass) == 0)
                                               {
                                                  dispose();
                                                  admpl = new adminpanel();
                                                  admpl.setVisible(true);
     
                                                }
                            else 
                                   {
                                      jPasswordField1.setText("");
                                      Toolkit.getDefaultToolkit().beep();
                                      JOptionPane.showMessageDialog(frame,
                                      "Check your password.\n\n" +
                                       "Please reenter or contact your system administrator.\n\n");
                                        
                           
                                    }
                            }
                            else{
                                   JOptionPane.showMessageDialog(frame,"Utilisateur incorrect");
                                   jPasswordField1.setText("");        
                                   jTextField1.setText("");
                                   
                }
            }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables


}